export const RATING_LABELS: Record<number, string> = {
  1: 'Very poor',
  2: 'Below average',
  3: 'Okay',
  4: 'Very good',
  5: 'Excellent!',
};

export const TONE_INFO: Record<number, { cls: string; label: string }> = {
  1: { cls: 'critical', label: 'Critical tone' },
  2: { cls: 'critical', label: 'Honest feedback' },
  3: { cls: 'neutral',  label: 'Balanced tone' },
  4: { cls: 'positive', label: 'Positive tone' },
  5: { cls: 'positive', label: 'Glowing praise' },
};

export const RATING_TAGS: Record<number, { label: string; text: string }[]> = {
  1: [
    { label: 'Poor Service',        text: ' The service was very poor and disappointing.' },
    { label: 'Long Wait Time',      text: ' Had to wait way too long without any update.' },
    { label: 'Unhelpful Staff',     text: ' The staff were unhelpful and inattentive.' },
    { label: 'Not Recommended',     text: ' I would not recommend this place to anyone.' },
    { label: 'Needs Improvement',   text: ' Major improvements are needed across the board.' },
    { label: 'Bad Experience',      text: ' Overall it was a bad experience from start to finish.' },
    { label: 'Poor Quality',        text: ' The quality was well below what was expected.' },
    { label: 'Overpriced',          text: ' Definitely not worth the price charged.' },
    { label: 'Communication Issues',text: ' Communication was poor and unclear throughout.' },
    { label: 'Unclean',             text: ' The place was not clean and felt poorly maintained.' },
  ],
  2: [
    { label: 'Below Average',       text: ' The overall experience was below average.' },
    { label: 'Inconsistent',        text: ' Service was inconsistent and unreliable.' },
    { label: 'Slow Response',       text: ' Response time was slower than expected.' },
    { label: 'Could Be Better',     text: ' There is definite room for improvement here.' },
    { label: 'Slightly Disorganized',text: ' The process felt a bit disorganized at times.' },
    { label: 'Underwhelming',       text: ' The experience was underwhelming overall.' },
    { label: 'Inattentive Staff',   text: ' Staff could have been more attentive and helpful.' },
    { label: 'Average at Best',     text: ' It felt average at best and lacked consistency.' },
    { label: 'Waiting Time',        text: ' The waiting time was longer than it should have been.' },
    { label: 'Minor Issues',        text: ' There were a few minor issues that need fixing.' },
  ],
  3: [
    { label: 'Decent',              text: ' It was a decent experience overall.' },
    { label: 'Average',             text: ' Everything was fairly average, nothing stood out.' },
    { label: 'Some Delays',         text: ' There were some delays but nothing too serious.' },
    { label: 'Room for Improvement',text: ' There is definitely scope to improve the experience.' },
    { label: 'Okay Staff',          text: ' The staff were okay, friendly enough.' },
    { label: 'Acceptable',          text: ' The service was acceptable for the price.' },
    { label: 'Fairly Comfortable',  text: ' The place was fairly comfortable to be in.' },
    { label: 'Meets Expectations',  text: ' It met basic expectations, nothing more.' },
    { label: 'Could Be Consistent', text: ' A bit more consistency would go a long way.' },
    { label: 'Would Revisit',       text: ' Might give it another try on a quieter day.' },
  ],
  4: [
    { label: 'Friendly Staff',      text: ' The staff were friendly and helpful throughout.' },
    { label: 'Good Service',        text: ' The service was good and smooth overall.' },
    { label: 'Clean Place',         text: ' The place was clean and well maintained.' },
    { label: 'Worth Visiting',      text: ' Definitely worth a visit if you are in the area.' },
    { label: 'Quick Service',       text: ' Service was quick and efficient.' },
    { label: 'Good Value',          text: ' Good value for the price paid.' },
    { label: 'Professional',        text: ' The team was professional and well organized.' },
    { label: 'Smooth Experience',   text: ' The whole experience was smooth and hassle free.' },
    { label: 'Recommended',         text: ' Would recommend this place to friends and family.' },
    { label: 'Good Quality',        text: ' The quality was good and met expectations well.' },
  ],
  5: [
    { label: 'Excellent Quality',   text: ' The quality was excellent and truly outstanding.' },
    { label: 'Exceptional Service', text: ' The service was exceptional from start to finish.' },
    { label: 'Friendly Staff',      text: ' The staff were extremely warm and welcoming.' },
    { label: 'Will Return',         text: ' Will definitely be coming back again.' },
    { label: 'Highly Recommend',    text: ' Highly recommend this place to everyone.' },
    { label: 'Professional Team',   text: ' The team was highly professional and attentive.' },
    { label: 'Great Atmosphere',    text: ' The atmosphere was lovely and very welcoming.' },
    { label: 'Exceeded Expectations',text: ' It exceeded all my expectations.' },
    { label: 'Spotlessly Clean',    text: ' The place was spotlessly clean and well kept.' },
    { label: 'Best Experience',     text: ' One of the best experiences I have had in a long time.' },
  ],
};